---

- name: Converge
  hosts: all
  become: "yes"
  roles:
    - deitkrachten.cron
  tasks:
    - name: Include role 'ansible-role-logrotate'
      ansible.builtin.include_role:
        name: ansible-role-logrotate
